// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJy_vgJMugnS107974SLLt61URdp3zsRQ',
    appId: '1:866608175485:web:24d1b013e674d036fe5414',
    messagingSenderId: '866608175485',
    projectId: 'imdb-54042',
    authDomain: 'imdb-54042.firebaseapp.com',
    storageBucket: 'imdb-54042.appspot.com',
    measurementId: 'G-FQYQ4KJBG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0sbboJ-zwI-Cm4H7klQwIEDSwz42_paA',
    appId: '1:866608175485:android:968e56bb19605888fe5414',
    messagingSenderId: '866608175485',
    projectId: 'imdb-54042',
    storageBucket: 'imdb-54042.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs2FxMsTzDFznENPsX4UmmhoKgsri-Z7Y',
    appId: '1:866608175485:ios:ce57bccc00e70dfffe5414',
    messagingSenderId: '866608175485',
    projectId: 'imdb-54042',
    storageBucket: 'imdb-54042.appspot.com',
    iosClientId: '866608175485-g0dsdksabe560ae67j3s1rn6nqmtpgdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.imdbDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs2FxMsTzDFznENPsX4UmmhoKgsri-Z7Y',
    appId: '1:866608175485:ios:ce57bccc00e70dfffe5414',
    messagingSenderId: '866608175485',
    projectId: 'imdb-54042',
    storageBucket: 'imdb-54042.appspot.com',
    iosClientId: '866608175485-g0dsdksabe560ae67j3s1rn6nqmtpgdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.imdbDemo',
  );
}
